version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MILVUS_URI=${MILVUS_URI}
      - MILVUS_TOKEN=${MILVUS_TOKEN}
      - SUPERMEMORY_API_URL=${SUPERMEMORY_API_URL}
      - SUPERMEMORY_API_KEY=${SUPERMEMORY_API_KEY}
    volumes:
      - ./backend:/app
    networks:
      - yuzuriha-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - yuzuriha-network

networks:
  yuzuriha-network:
    driver: bridge